### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/practica-de-visual-studio-Lissete7#2]
[Practica02_Lizzete León González.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Lissete7/files/6161391/Practica02_Lizzete.Leon.Gonzalez.pdf)

**Comment by DuilioAquino10** [comment]
Calificación 20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
